export const lang = {
  appNameText: "Wallet App",
  homeText: "Home",
  transactionsText: "Transactions",
  investmentsText: "Investments",
  dashboardText: "Dashboard",
  hiText: "Hi",
  addTransactionText: "Add Transaction",
  editTransactionText: "Edit Transaction",
  incomeText: "Income",
  expenseText: "Expense",
  transferText: "Tranfer",
  account: "Account",
  category: "Category",
  recurrentPay: "Recurrent",
  allText: "All",
  lastTransacionsText: "Last Transactions",
  topCategoriesText: "Top Most Expensive Categories",
  monthChartText: "Balace - Last 30 days -",
  descriptionTableText: "Description",
  categoryTableText: "Category",
  dateTableText: "Date",
  amountTableText: "Amount",
  searchTransactionText: "Search transactions...",
  cancel: "Cancel",
  recurrent: "Recurrent",
  acceptText: "Accept",
  footerText: "Application made by Julian Prieto",
};
