export const lang = {
  appNameText: "WALLE&TRX",
  homeText: "Home",
  transactionsText: "Transactions",
  investmentsText: "Investments",
  dashboardText: "Dashboard",
  accountsText: "Accounts",
  settingsText: "Settings",
  hiText: "Hi",
  addTransactionText: "Add Transaction",
  editTransactionText: "Edit Transaction",
  incomeText: "Income",
  expenseText: "Expense",
  transferText: "Tranfer",
  account: "Account",
  category: "Category",
  recurrentPay: "Recurrent",
  allText: "All",
  lastTransacionsText: "Last Transactions",
  topCategoriesText: "Top Most Expensive Categories",
  monthChartText: "Last 30 days Balance",
  descriptionTableText: "Description",
  categoryTableText: "Category",
  dateTableText: "Date",
  amountTableText: "Amount",
  searchTransactionText: "Search transactions...",
  cancel: "Cancel",
  recurrent: "Recurrent",
  acceptText: "Accept",
  footerText: "Application made by Julian Prieto",
  accountSummaryText: "Accounts",
  balanceText: "Balance",
  addAccountText: "Add Account",
  noAccountMessage: "You don't have any account yet, create one in ",
};
